package main

import (
	"strings"

	"github.com/charmbracelet/bubbles/list"
	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/lipgloss"
)

// the DetailsModel only serves to show an event's details in a pretty way, and
// nothing more
type DetailsModel struct {
	list   list.Model
	styles DetailsStyles
}

var detailModelStyle = lipgloss.NewStyle()

func NewDetailsModel(listModel list.Model) tea.Model {
	s := DefaultDetailsStyles()
	return DetailsModel{
		list:   listModel,
		styles: s,
	}
}

func (m DetailsModel) Init() tea.Cmd {
	return nil
}

func (m DetailsModel) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	return m, nil
}

// FIXME: details view not updating when hovering different items in the list
// component
func (m DetailsModel) View() string {
	var summary, course, date string

	items := m.list.Items()
	if i, ok := items[m.list.Cursor()].(Event); ok {
		summary = i.Summary
		course = i.Course
		date = i.GetFormattedStartDate()
	}

	s := &strings.Builder{}
	WriteStringf(s, "%s\n\n", m.styles.Title.Render("Event Details"))
	WriteStringf(s, "\n%s %s\n",
		m.styles.DueDateLabel.Render("Due Date:"),
		m.styles.DueDate.Render(date))
	WriteStringf(s, "\n%s %s\n",
		m.styles.SummaryLabel.Render("Classwork:"),
		m.styles.Summary.Render(summary))
	WriteStringf(s, "\n%s %s\n",
		m.styles.CourseLabel.Render("For Course:"),
		m.styles.Course.Render(course))

	return m.styles.Model.Render(s.String())
}

// DetailsStyles contains style definitions for the details component. these
// values are generated by DefaultStyles.
type DetailsStyles struct {
	Title,
	Model,
	DueDate,
	DueDateLabel,
	Summary,
	SummaryLabel,
	Course,
	CourseLabel lipgloss.Style
}

// DefaultDetailsStyles generates styles for DetailsModel
func DefaultDetailsStyles() (s DetailsStyles) {
	s.Title = lipgloss.NewStyle().
		Padding(0, 1).
		Background(lipgloss.Color(termANSIBrightYellow.String())).
		Foreground(lipgloss.Color(termANSIBlack.String()))

	s.Model = lipgloss.NewStyle().Padding(0, 2)

	s.DueDate = lipgloss.NewStyle().Foreground(lipgloss.Color(termANSIRed.String()))
	s.DueDateLabel = lipgloss.NewStyle().
		Padding(0, 1).
		Background(lipgloss.Color(termANSIRed.String())).
		Foreground(lipgloss.Color(termANSIWhite.String()))

	s.Summary = lipgloss.NewStyle().Foreground(lipgloss.Color(termANSIWhite.String()))
	s.SummaryLabel = lipgloss.NewStyle().
		Padding(0, 1).
		Background(lipgloss.Color(termANSIBlack.String())).
		Foreground(lipgloss.Color(termANSIBrightWhite.String()))

	s.Course = lipgloss.NewStyle().Foreground(lipgloss.Color(termANSIWhite.String()))
	s.CourseLabel = lipgloss.NewStyle().
		Padding(0, 1).
		Background(lipgloss.Color(termANSIBlack.String())).
		Foreground(lipgloss.Color(termANSIBrightWhite.String()))

	return s
}
